### ISSUE TITLE
meet grid view not working anymore, when will it have a new update?

### ISSUE THREAD

**Issue by ayanez739p** [Fugiman/google-meet-grid-view#213] opened 2020-06-15 19:57 UTC
_Before opening an issue, please check the existing open issues to see if somebody has already reported it! If something is horribly wrong, like all videos showing up in a single column, chances are somebody already reported it. Please reply in that issue instead._

**Describe what is broken**
A clear and concise description of what isn't working.

**Expected behavior**

**Screenshots**

**Software used:**
 - OS [e.g. Windows 10]:
 - Browser [e.g. Chrome, Firefox]:
 - Version [e.g. 22]:
 - Extension [e.g. Official Chrome Extension, Tampermonkey]:
 - Grid View Version [e.g. 1.19, 1.23]:

**Additional context**

**Comment by kristylg** [comment] 2020-06-15 21:56
Google Meet Grid View is not working. I can only see six students in a panel when in presentation mode, and I usually can see all 25. If I try to see  25, it puts the students in a vertical line, and I still cannot see 25 kids and they are so tiny! Please assist! It has been working GREAT for these past few months, and it would be so sad to end the year with it not working and not being able to see my students. Thank you!

**Comment by anne-nelson** [comment] 2020-06-15 22:01
@ayanez739p This is a duplicate of #202 , please check for open issues before creating a new one.

@kristylg Adding comments just to effectively say "me too" isn't helpful, it just spams the author. Just +1 the original issue if it's happening to you as well and you have no extra helpful information.

**Comment by pablogirado** [comment] 2020-06-15 23:49
Not working

**Comment by Fugiman** [comment] 2020-06-17 01:24
(Maybe) fixed in v1.36, please update.

**Closed by Fugiman** 2020-06-17 01:24 UTC
Labels: broken
