### ISSUE TITLE
GRID IS NOT WORKING 

### ISSUE THREAD

**Issue by shabbirdudhiya** [Fugiman/google-meet-grid-view#260] opened 2020-07-03 04:16 UTC
Grid view in not as expected
my grid view is not working as expected ....it is showing all participants in a list form.....it is not titled......help me to solve the issue........i tried 3 times reinstalling the extension.......

**Comment by 127001** [comment] 2020-07-03 07:45
Duplicate of https://github.com/Fugiman/google-meet-grid-view/issues/241

**Comment by YpePoortinga** [comment] 2020-07-03 08:44
Same here

**Closed as completed** 2020-07-03 09:24 UTC
Labels: broken
