### ISSUE TITLE
la grid di meet

### ISSUE THREAD

**Issue by raguconfezionato** [Fugiman/google-meet-grid-view#134] opened 2020-05-25 07:19 UTC
fino a ieri funzionava bene, oggi tutto bloccato.
non so nulla di programmazione, help me

**Comment by Xinne** [comment] 2020-05-25 07:32
Duplicate of #133

**Comment by Fylls** [comment] 2020-05-25 07:35
translation: 

>" It was working until yesterday. strangely today it is all broken.
>  I don't know anything about coding please help me out"

**Comment by Fugiman** [comment] 2020-05-25 12:49
As Xinne said, this is a duplicate of #133

**Closed by Fugiman** 2020-05-25 12:49 UTC
Labels: broken
