### ISSUE TITLE
Grid view broken

### ISSUE THREAD

**Issue by nizaaa** [Fugiman/google-meet-grid-view#129] opened 2020-05-23 06:35 UTC
**Describe what is broken**
Grid view is not broken. 

**Expected behavior**
Grid view list to check on students' exam

**Screenshots**
![image](https://user-images.githubusercontent.com/65803855/82723505-a0653b00-9cf9-11ea-9f87-c9002f2cc6eb.png)

**Software used:**
 Use chrome 

**Additional context**
I am writing from Cambodia. It's important. We need grid view to invigilate exam online but now it's broken. The exam is tomorrow. I know you've been working on this. I really hope you could fix it as soon as possible. It's a big exam one. Please help. Thank you very much for your effort.

**Comment by Fugiman** [comment] 2020-05-23 06:55
Duplicate of #126

**Closed by Fugiman** 2020-05-23 06:55 UTC
Labels: broken
