### ISSUE TITLE
Grid View seems to be broken

### ISSUE THREAD

**Issue by sayedarifuddin** [Fugiman/google-meet-grid-view#203] opened 2020-06-15 06:54 UTC
**Describe what is broken**
When enabled, some participants are shown parallelly. (Default settings)

Recent Meet UI update seems to be the reason for this problem. https://github.com/Fugiman/google-meet-grid-view/issues/202#issuecomment-643956826
![image](https://user-images.githubusercontent.com/47639147/84637699-d3c17100-af17-11ea-8693-78d97faccbdf.png)

**Software used:**
 - Windows 10
 - Microsoft Edge Canary
 - Version 85.0.545.0 (Official build) canary (64-bit)
 - Official Chrome Extension
 - Grid View v1.35.0

**Comment by SmartToilet** [comment] 2020-06-15 07:07
Same thing happened to me too. Hope it get fixed.

**Comment by flm1972** [comment] 2020-06-15 07:18
Same thing for me.
Please solve it. Txssss

**Comment by RiZKiT** [comment] 2020-06-15 07:32
Duplicate of https://github.com/Fugiman/google-meet-grid-view/issues/202!?

**Comment by sayedarifuddin** [comment] 2020-06-15 14:21
v1.36 fixed the issue. https://github.com/Fugiman/google-meet-grid-view/issues/202#issuecomment-644068312 Thanks! @Fugiman

**Comment by sayedarifuddin** [comment] 2020-06-16 05:58
Update v1.36.0 causing Unresponsive Pages and causing the Browser to crash. 
Also when the extension works, the UI is still broken like v1.35.0

**Software used:**
 - Windows 10
 - Microsoft Edge Canary
 - Version 85.0.548.0 (Official build) canary (64-bit)
 - Official Chrome Extension
 - Grid View v1.36.0

**Comment by FugiTech** [comment] 2020-06-17 08:10
On June 14th Google updated Meet with changes to the Tiled view, breaking the Grid View extension. I quickly diagnosed the issue and released a fix as v1.36. However I did not test this fix in a large meeting, which led to browsers hanging or crashing for many users in meetings over 16 people. This was caused by the google code assuming a maximum of 16 videos and entering an infinite loop. I'm extremely sorry I did not test this change thoroughly enough to discover this issue before releasing v1.36.

As of now I am releasing v1.37 which properly fixes the issue. I would like to thank @rogerl19 and his coworkers for hosting a meeting in which I could test this change. In addition to fixing the crash and restoring the expected functionality, it also will automatically lower video quality in large meetings to try and avoid the freezing some users have reported. If the automatic quality is not to your liking, you can override it in the Advanced Settings.

Please note that versions must be reviewed by Google and I do not control how long it takes. **Until the review is complete you can fix the issue by setting your meet layout to Sidebar.** Thanks to @ivanmalgra for finding this fix.

Once again I apologize for the issues caused by my extension, and will endeavor to do better in the future. If you have issues with v1.37 please comment in #225

**Closed by FugiTech** 2020-06-17 08:10 UTC
Labels: broken
