### ISSUE TITLE
Grid View putting videos into vertical column instead of grid

### ISSUE THREAD

**Issue by misscece** [Fugiman/google-meet-grid-view#125] opened 2020-05-22 20:53 UTC
Today, all of our school's class Meets using Grid View noticed the layout changed to put the Meet Videos into horizontal bars across the screen (screenshot below). Large classes were not able to see many students because of this issue. I tested the extension on a different Chrome profile and the Grid View extension was working like normal (screenshot below). Help? I've uninstalled and re-installed the extension for all in our school domain, twice now. Stuck on other things to try.

Expected view: 
![Screen Shot 2020-05-22 at 12 47 11 PM](https://user-images.githubusercontent.com/65788683/82708595-7ea18080-9c33-11ea-972a-2f534781ae24.png)

Today's view:
![Screen Shot 2020-05-22 at 1 26 26 PM](https://user-images.githubusercontent.com/65788683/82708628-911bba00-9c33-11ea-9efe-c6cfc50e359a.png)

**Software used:**
 - OS [e.g. Windows 10]: MacOS (Catalina)
 - Browser [e.g. Chrome, Firefox]: Chrome
 - Version [e.g. 22]: 81.0.4044.138
 - Extension [e.g. Official Chrome Extension, Tampermonkey]: tried both Official Chrome Extension & stgnola.org versions, our school primarily uses stgnola.org version
 - Grid View Version [e.g. 1.19, 1.23]: stgnola.org vsn 2020.4.30; Official Chrome Extension vsn 1.30.0

**Comment by Fugiman** [comment] 2020-05-23 05:07
duplicate of #126

**Closed by Fugiman** 2020-05-23 05:07 UTC
Labels: broken
