### ISSUE TITLE
Google meet grid view extension is broken 

### ISSUE THREAD

**Issue by JayBeckitt** [Fugiman/google-meet-grid-view#237] opened 2020-06-20 19:49 UTC
Hi,

V1.37 of meet grid view is crashing with more than 2 people on the call. It stops the browser working, locks you out of all controls and kicks you out of the meeting and duplicates you when you try to go back in. 

I've tried the suggested fix of spotlight view and this doesn't work for me, same thing happens - browser crashes and I get kicked out. Then can't get in using the browser again. 

I was expecting this to work as normal with as many people in the meeting as usual in grid view. 

**Software used:**
 - OS Windows 10
 - Browser Chrome, Firefox
 - Version (latest one) 
 - Extension Official Chrome Extension
 - Grid View Version 1.37

**Additional context**

**Comment by annedroiid** [comment] 2020-06-22 07:48
@JayBeckitt This is a duplicate of #225, please close this issue and follow along there.

**Closed as completed** 2020-06-22 15:09 UTC
Labels: broken
