### ISSUE TITLE
Names missing

### ISSUE THREAD

**Issue by mm104** [Fugiman/google-meet-grid-view#146] opened 2020-05-26 16:40 UTC
I use grid view daily for my class. Today, it took a lot of clicking to get all of my students on the screen. I don't even know what I clicked to make it work. Their names did not show up unless I had the white bar showing at the bottom of the screen, which cut off half of the bottom row. Most of my students turn off their videos and often change their avatars, so I need the names so I know who is on.

**Comment by Gass-by-Revi** [comment] 2020-05-26 16:46
> Yo uso la vista de cuadrícula diariamente para mi clase. Hoy, me costó mucho hacer clic para que todos mis alumnos aparecieran en la pantalla. Ni siquiera sé en qué hice clic para que funcione. Sus nombres no aparecían a menos que tuviera la barra blanca en la parte inferior de la pantalla, que cortaba la mitad de la fila inferior. La mayoría de mis alumnos apagan sus videos y, a menudo, cambian sus avatares, por lo que necesito los nombres para saber quién está.

@mm104 no es ningún error lo de no ver los nombre. Para que no le ocurra debe desactivar el modo mosaico. Adjunto una foto para que lo vea mejor.
![Screenshot 2020-05-26 at 18 45 41](https://user-images.githubusercontent.com/64775775/82927530-23e48d80-9f81-11ea-935b-e9d671ec27d7.png)

**Comment by Gass-by-Revi** [comment] 2020-05-26 16:47
@mm104 If you don't understand me, please tell me

**Comment by mm104** [comment] 2020-05-26 16:58
It looks like you are giving the directions for fixing the grid view. I figured that out. I need the names to appear on the screen all the time, not just when the meeting details bar is on.

**Comment by Gass-by-Revi** [comment] 2020-05-26 17:05
ok, in the photo, do you see where puts "automatico"? you have to click there when you are at the meeting. Do you know how to get there?
![Screenshot 2020-05-26 at 19 05 15](https://user-images.githubusercontent.com/64775775/82929389-dc133580-9f83-11ea-99d6-4ab2b150aa12.png)

**Comment by mm104** [comment] 2020-05-26 17:09
I have that clicked. The grid view worked, but the names no longer show all the time.

**Comment by Gass-by-Revi** [comment] 2020-05-26 17:12
That doesn't happen to me, only if I have mosaic mode on. Which version do you have?

**Comment by mm104** [comment] 2020-05-26 17:17
I updated it today.

**Comment by Gass-by-Revi** [comment] 2020-05-26 17:22
Is the version v1.32?  I don't think it affects, because it worked for me with the previous version.

**Comment by mm104** [comment] 2020-05-26 17:23
It worked for me until today, which is why I reported the issue.

**Comment by Gass-by-Revi** [comment] 2020-05-26 17:36
ok, I'm going to investigate that, when I know what happens, I tell you.
But may be @Fugiman tell you a solution previously.

**Comment by Eagle-Man** [comment] 2020-05-26 18:26
@mm104 Can you post a picture of what you are experiencing?  I haven't had any issues with 1.32.

**Comment by Gass-by-Revi** [comment] 2020-05-26 18:31
> @ mm104 ¿Puedes publicar una foto de lo que estás experimentando? No he tenido ningún problema con 1.32.

Yo tampoco

**Comment by Fugiman** [comment] 2020-05-26 22:55
@mm104 If the bottom bar is cutting off part of the grid then you likely aren't using v1.32 or haven't enabled the extension's grid view. A screenshot with the grid view menu open would be useful in figuring this out. Also, how many people were in the meeting? Thanks.

**Comment by Fugiman** [comment] 2020-05-27 02:46
I've confirmed that names will go missing if the video get very small. A fix for this will be in v1.33.

**Closed by Fugiman** 2020-05-27 02:46 UTC
Labels: broken

**Comment by thushariii** [comment] 2021-02-03 10:17
> @mm104 Can you post a picture of what you are experiencing? I haven't had any issues with 1.32.

apparently, this issue is still not resolved. I encountered this a few days ago. This only happens when you switch to tiled view. Would like to know whether there is any solution. 

![ab](https://user-images.githubusercontent.com/55043879/106731802-f4b90c80-6635-11eb-9bbb-b6e154a16e1a.PNG)

**Comment by Eagle-Man** [comment] 2021-02-04 01:33
Tiled view is a Google Meet setting, not a Grid View setting.  It is the intended behaviour (by Google) for the names to disappear after moments of inactivity.  if you move the mouse, then it should appear again for a bit.  But also, you either don't have Grid View installed, in your browser, or the extension has been disabled since the Grid View options icon is not present beside the People icon.

**Comment by thushariii** [comment] 2021-02-04 03:26
okay, thanks for the info. The issue was I couldn't see the names or who's talking at all, before taking this screenshot but it only happened yesterday. I might have encountered some glitch.
