### ISSUE TITLE
Asking to resolve the following isssue

### ISSUE THREAD

**Issue by nikhil78787** [Fugiman/google-meet-grid-view#206] opened 2020-06-15 09:10 UTC
Hi, There 
Recently I have installed google chrome grid view, it worked well for a few days, 
But today morning I attended an important meeting and turned on the grid view option,
I was amazed to see weird thing happened on my screen, that was the people participating in the meeting were arranged in a row but  that's not the daily scenario,
people were side by side which looks comfortable for me to view all faces.

My friend too faced that problem today

conclusion: I request you to resolve the problem if it's from your side, if not 
plz mail me the solution and I would try to resolve the issue if it is from my side
my email :nikhilnaraharasetti787@gmail.com

[FireShot Pro Screen Capture #019 - 'Meet - dit-npdm-zbk' - meet_google_com.pdf](https://github.com/Fugiman/google-meet-grid-view/files/4779183/FireShot.Pro.Screen.Capture.019.-.Meet.-.dit-npdm-zbk.-.meet_google_com.pdf)

**Comment by filipc** [comment] 2020-06-15 09:12
copy of #202

**Comment by OChavez3** [comment] 2020-06-15 19:50
Hello, 
   I had the same issue during my Google Meet with my students today. I was not able to see myself in the grid. The students appeared on tiles that were vertically in a row. Please let me know how I am able to resolve this issue.

**Comment by anne-nelson** [comment] 2020-06-15 22:03
@OChavez3 This issue is a duplicate of #202 and posting to effectively say "me too" just spams the author. If you are also having a problem you should just +1 the original post.

**Comment by Fugiman** [comment] 2020-06-17 01:19
(Maybe) fixed in v1.36, please update.

**Closed by Fugiman** 2020-06-17 01:19 UTC
Labels: enhancement
