### ISSUE TITLE
Multiple issues with Firefox

### ISSUE THREAD

**Issue by meyertime** [Fugiman/google-meet-grid-view#70] opened 2020-04-16 20:34 UTC
First of all, thanks for this really useful user script!!

I see some other issues floating around here which are similar, but they seem to be things that worked before but stopped working recently.  Whereas I started using it on Firefox April 2nd and these features never worked from the beginning.  I installed it through greasyfork, so it has been auto-updating ever since.  I have the latest version 1.18 now.

- `Only show participants with video` makes no difference.  It seems to show participants whether or not they have video either way.
- `Include yourself in the grid` makes no difference.  It never includes yourself.
- There seems to be a limit to how many participants are shown.  Typically it's 8 for me.  I'm not sure if this is intended or not, but my colleagues, most of which are using Chrome, don't have that problem and can see everyone.  However, I found out that if I scale Firefox down in order to make the code think that my screen is bigger, I can see more participants.  Right now I'm using a 1920x1200 screen at 1x scale.  If there is a limit based on screen size, it would be nice to be able to configure it.  It also seems odd that it's not like that on Chrome.

Any guidance would be appreciated.  Thanks!  Here are a few of the similar issues:

https://github.com/Fugiman/google-meet-grid-view/issues/59
https://github.com/Fugiman/google-meet-grid-view/issues/56
https://github.com/Fugiman/google-meet-grid-view/issues/54
https://github.com/Fugiman/google-meet-grid-view/issues/53
https://github.com/Fugiman/google-meet-grid-view/issues/41

Even though these are technically still open, they appear to have been fixed in the latest version, and they worked before.  I'm wondering if maybe it was fixed in a way that works for Chrome but not Firefox?

**Comment by Fugiman** [comment] 2020-04-16 20:41
Please share your firefox version, operating system version, and try disabling any other extensions & scripts running on the page. On Windows 10, Firefox 75.0 the script works as expected. I've heard reports from other Firefox users that it does not work but I've been unable to reproduce it.

As a workaround, zooming out will show more participants. The underlying issue is that the script is unable to hook into the rendering pipeline and so all you are getting is the CSS re-positioning of existing video elements, which Google limits based on screen size by default.

**Comment by meyertime** [comment] 2020-04-16 21:12
Thanks for that explanation; that makes sense.

Firefox 75.0 on Arch Linux.  Arch Linux does not have versions; it's rolling release, so... latest.

I tried disabling all other extensions, and this is the only user script I have currently.  Still not working.

However, I installed Chrome and tried it, and it works.  However, they don't have Greasemonkey for Chrome, only Tampermonkey.  That got me thinking: I wonder if it's a problem with Greasemonkey?

I disabled Greasemonkey and installed Tampermonkey on Firefox and installed the script.  It's working now!  So apparently it has something to do with a difference between those extensions.

While I do have a workaround, it would be nice if I could go back to Greasemonkey, since it's open source.  For reference:

Greasemonkey 4.9 (4/2/2020)
Tampermonkey 4.10.6112 (4/16/2020)

**Comment by Fugiman** [comment] 2020-04-16 21:18
Excellent, thank you for the report!

If you're interested I just released an official Firefox extension that you could try as well: https://addons.mozilla.org/en-US/firefox/addon/google-meet-gridview/ - even if you'd prefer to keep using greasemonkey I'd appreciate if you gave it a try and let me know if it works on Arch Linux :)

**Comment by meyertime** [comment] 2020-04-16 22:26
Sure, I have a meeting tomorrow and I'll test the Firefox extension then.  I'll also try Violentmonkey, as that's another open source option.

I like the idea of using a user script manager, as it could reduce the number of extensions I need to have if I find other user scripts I'd like to use.  So I might look into why it's not working with Greasemonkey.  (I write code for a living.)  Do you have any tips for debugging?  I'm not seeing any log entries in the console related to the grid view script even though I see there's code that writes log entries.  Also if you could point me in the right direction as to where in the code "the script is unable to hook into the rendering pipeline", that would be super helpful.  Thanks!

**Comment by Fugiman** [comment] 2020-04-17 06:21
Turns out greasemonkey (unlike TamperMonkey and ViolentMonkey) runs scripts in a sandbox that doesn't have access to `window`. The solution is for the script to re-inject itself into the page, similar to how the extensions run. This should be fixed in v1.21

**Closed by Fugiman** 2020-04-17 06:21 UTC

**Comment by meyertime** [comment] 2020-04-18 08:21
Thanks for fixing the Greasemonkey issue! I'll test it out Monday.

I confirmed that the Firefox extension works on my setup. 👍

**Comment by meyertime** [comment] 2020-04-23 16:44
Just confirming it's fixed in Greasemonkey now.  Thanks again!
